#!/usr/bin/bash
mkdir -p static/doc
mkdir -p static/img/{info,post,portfolio}
cp -f .env.example .env
session_secret=$(openssl rand -base64 32)
sed -i "s|^SESSION_SECRET=.*|SESSION_SECRET=\"$session_secret\"|" ".env"
read -p "Admin Email: " new_email
read -p "Admin Password: " new_password
sed -i "s|^const EMAIL = '.*';|const EMAIL = '$new_email';|" "prisma/seed.ts"
sed -i "s|^const PASSWORD = '.*';|const PASSWORD = '$new_password';|" "prisma/seed.ts"
pnpm install
pnpm exec prisma generate
pnpm exec prisma migrate deploy
pnpm exec prisma db seed
pnpm run build